"""
Agent-to-Agent (A2A) Protocol Schema.

Defines Pydantic models for inter-agent communication, structured task delegation,
performative primitives, and payload artifacts in the CartFlow checkout engine.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
import uuid
from pydantic import BaseModel, Field


class PerformativeEnum(str, Enum):
    """FIPA-inspired agent performative intent types."""
    REQUEST = "REQUEST"          # Ask another agent to perform an action or computation
    INFORM = "INFORM"            # Supply factual data or task execution results
    PROPOSE = "PROPOSE"          # Offer an action/discount proposal subject to confirmation
    CONFIRM = "CONFIRM"          # Confirm agreement with a proposal
    REJECT = "REJECT"            # Decline a proposal
    FAILURE = "FAILURE"          # Signal an execution failure or exception state


class AgentID(str, Enum):
    """Identifiers for agents participating in the checkout network."""
    CONCIERGE = "concierge"
    DISCOVERY = "discovery"
    RETENTION = "retention"
    CHECKOUT = "checkout"
    CUSTOMER = "customer"


class ProductItem(BaseModel):
    """Schema for product catalog recommendations."""
    product_id: str
    variant_id: str
    title: str
    price: float
    currency: str = "USD"
    category: str = "General"
    inventory_quantity: int = 10
    score: float = 1.0


class RiskAssessment(BaseModel):
    """Customer churn and abandonment risk profile from Databricks."""
    customer_id: str
    loyalty_tier: str = "STANDARD"  # STANDARD, GOLD, PLATINUM
    ltv_score: float = 100.0
    churn_risk_score: float = 0.5   # 0.0 (low) to 1.0 (high)
    risk_level: str = "MEDIUM"       # LOW, MEDIUM, HIGH
    hesitation_detected: bool = False
    max_authorized_discount_pct: float = 10.0


class DiscountOffer(BaseModel):
    """Margin-safe personalized discount offer generated by Retention Agent."""
    discount_code: str
    discount_pct: float
    max_authorized_pct: float
    applied: bool = False
    reason: str = "Retention Incentive"


class CheckoutDetails(BaseModel):
    """Final 1-click cart and checkout details generated by Checkout Agent."""
    cart_id: str
    checkout_url: str
    subtotal: float
    discount_amount: float = 0.0
    total: float
    currency: str = "USD"
    discount_code: Optional[str] = None
    status: str = "created"


class Artifacts(BaseModel):
    """Container for structured artifacts exchanged between agents."""
    recommendations: List[ProductItem] = Field(default_factory=list)
    risk_assessment: Optional[RiskAssessment] = None
    discount_offer: Optional[DiscountOffer] = None
    checkout_details: Optional[CheckoutDetails] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TaskRequest(BaseModel):
    """Structured task specification delegated via A2A message."""
    task_id: str = Field(default_factory=lambda: f"task_{uuid.uuid4().hex[:8]}")
    goal: str
    customer_id: str
    query: Optional[str] = None
    cart_items: List[Dict[str, Any]] = Field(default_factory=list)
    discount_code: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class A2AMessage(BaseModel):
    """
    Standardized Agent-to-Agent JSON Message Envelope.
    """
    message_id: str = Field(default_factory=lambda: f"msg_{uuid.uuid4().hex[:12]}")
    conversation_id: str = Field(default_factory=lambda: f"conv_{uuid.uuid4().hex[:8]}")
    sender: AgentID
    receiver: AgentID
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    performative: PerformativeEnum
    content: str
    task: Optional[TaskRequest] = None
    artifacts: Artifacts = Field(default_factory=Artifacts)
